In [1]:
import tensorflow as tf

C:\Users\Dito\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
tf.__version__

'2.15.0'

In [4]:
import tensorflow as tf

# Membuat sebuah konstanta
hello = tf.constant("Hello, World!")

# Menjalankan operasi dan mencetak hasilnya
result = hello.numpy()
print(result.decode())


Hello, World!


In [5]:
# Membuat tensor berisi angka 1 (atau 0)
tensor_onefull = tf.ones([4, 4, 4, 1])
print(tensor_onefull)

# Membuat tensor berisi angka 0
tensor_zerofull = tf.zeros([5, 5])
print(tensor_zerofull)

# Mengambil nilai spesifik dari tensor (mirip dengan slicing pada pemrograman konvensional)
tensor_sliced_onefull = tensor_onefull
print(tensor_sliced_onefull)

# Mengambil nilai dari posisi tertentu pada tensor zerofull
tensor_sliced_zerofull = tensor_zerofull[0, 1]
print(tensor_sliced_zerofull)


tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(4, 4, 4, 1), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   